version: '3.7'
services:
  mysql_db_container: # 数据库容器
    image: mysql:latest # 镜像 mysql的最新版本
    command: --default-authentication-plugin=mysql_native_password # 启动的命令
    environment: # 环境变量
      MYSQL_ROOT_PASSWORD: rootpassword  # root账号密码 这里密码要写在.env配置文件中，防止git提交
    ports:
      - 3306:3306 # 内部端口和外部端口
    volumes:
      - mysql_db_data_container:/var/lib/mysql # 数据存储的地址
  adminer_container: # 管理工具容器
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container: